version: '2'
services:
  tiller:
    build:
      context: ./build
    container_name: tiller
    image: eugenmayer/tiller-test:consul
    volumes:
      - ./build/tiller:/etc/tiller
    ports:
      - "8500:8500"
    environment:
      - TILLER_ENV='production'
