version: '2'
services:
  tiller:
    build:
      context: ./build
    container_name: tiller
    image: eugenmayer/tiller-test:execonwrite
    volumes:
      - ./build/tiller:/etc/tiller
    environment:
      use_develop: 'false'

  tiller_dev:
    container_name: tiller_dev
    image: eugenmayer/tiller-test:execonwrite
    volumes:
      - ./build/tiller:/etc/tiller
    environment:
      use_develop: 'true'
